import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [message, setMessage] = useState(""); // Utilisation de l'état pour stocker le message
  const [loading, setLoading] = useState(true); // Pour afficher un message de chargement pendant la récupération

  useEffect(() => {
    // Effectuer l'appel fetch vers l'API hello
    const fetchMessage = async () => {
      try {
        const response = await fetch("/api/hello");
        if (response.ok) {
          const data = await response.json();
          setMessage(data.name);  // Mettre à jour l'état avec le message de l'API
          console.log('+++MSG+++: ', data)

        } else {
          setMessage("Erreur lors de la récupération des données.");
        }
      } catch (error) {
        setMessage("Erreur réseau.");
      } finally {
        setLoading(false); // Une fois que la requête est terminée (qu'elle réussisse ou échoue), on met fin au chargement
      }
    };

    fetchMessage();  // Appeler la fonction fetchMessage lorsque le composant est monté
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />

          {/* Affichage conditionnel */}
          {loading ? (
            <p>Chargement...</p> // Afficher un message de chargement pendant que l'API est appelée
          ) : (
            <h1>{message}</h1> // Une fois que l'API a répondu, afficher le message
          )}
        </main>
      </div>
    </>
  );
}
